graph TB
    A[Start] --> B{foreach\nresource}
    B --> C[exists\ncheck]
    C --> D{resource\nexists?}
    D -- Yes --> E[run update\nor createorupdate query]
    D -- No --> F[run create\nor createorupdate query]
    E --> G[run statecheck check]
    F --> G
    G --> H{End}
  