/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    {
      type: 'doc',
      id: 'index', 
      label: 'Overview',
    },
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/quick-start-guide',
        'getting-started/creating-your-first-stack',
        'getting-started/deploying-your-first-stack',
      ],
    },
    {
      type: 'category',
      label: 'CLI Command Reference',
      items: [
        'cli-reference/build',
        'cli-reference/init',
        'cli-reference/teardown',
        'cli-reference/test',
        'cli-reference/info',
        'cli-reference/upgrade',
      ],
    },
    {
      type: 'category',
      label: 'Manifest File',
      items: [
        'manifest-file/manifest-structure',
        'manifest-file/resource-definitions',
        'manifest-file/using-globals',
      ],
    },
    {
      type: 'category',
      label: 'Resource Query Files',
      items: [
        'stackql-queries/query-anchors',
        'stackql-queries/query-options',
        'stackql-queries/advanced-query-techniques',
      ],
    },
    {
      type: 'category',
      label: 'Deployment',
      items: [
        'deployment/github-actions',
      ],
    },

    {
      type: 'category',
      label: 'Template Library',
      link: {
        type: 'generated-index',
        title: 'Template Library',
        description: 'stackql-deploy quick starts, how-tos, practical examples and use cases',
        slug: '/template-library',
        keywords: ['quickstarts', 'guides', 'how-tos', 'examples', 'use cases'],
        image: '/img/stackql-cover.png',
      },
      items: [
        {
          type: 'category',
          label: 'AWS',
          description: 'Practical examples and use cases specific to AWS',
          customProps: {
            icon: '/img/providers/aws/aws.png',
          },
          link: {
            type: 'generated-index',
            title: 'stackql-deploy AWS Templates',
            description: 'Practical examples and use cases specific to AWS',
            slug: '/template-library/aws',
          },
          items: [{ type: 'autogenerated', dirName: 'template-library/aws' }],
        },
        {
          type: 'category',
          label: 'Microsoft Azure',
          description: 'Practical examples and use cases specific to Azure',
          customProps: {
            icon: '/img/providers/azure/azure.png',
          },          
          link: {
            type: 'generated-index',
            title: 'stackql-deploy Azure Templates',
            description: 'Practical examples and use cases specific to Azure',
            slug: '/template-library/azure',
          },
          items: [{ type: 'autogenerated', dirName: 'template-library/azure' }],
        },
        {
          type: 'category',
          label: 'Google Cloud Platform',
          description: 'Practical examples and use cases specific to Google Cloud',
          customProps: {
            icon: '/img/providers/google/google.png',
          },          
          link: {
            type: 'generated-index',
            title: 'stackql-deploy Google Templates',
            description: 'Practical examples and use cases specific to Google Cloud',
            slug: '/template-library/google',
          },
          items: [{ type: 'autogenerated', dirName: 'template-library/google' }],
        },
      ],
    },

    // 

    // {
    //   type: 'category',
    //   label: '',
    //   items: [
    //     {
    //       type: 'category',
    //       label: 'AWS',
    //       items: [
    //         {
    //           type: 'doc',
    //           id: 'template-library/aws/simple-vpc',
    //           label: 'Simple VPC',
    //         },
    //       ],
    //     },
    //     {
    //       type: 'category',
    //       label: 'Azure',
    //       items: [
    //         {
    //           type: 'doc',
    //           id: 'template-library/azure/simple-vnet',
    //           label: 'Simple VNet',
    //           // customProps: {
    //           //   icon: '/img/azure-icon.png',  // Path to your Azure icon
    //           //   description: 'Deploy a basic Virtual Network in Azure with subnet configuration.',
    //           // },
    //         },
    //       ],
    //     },
    //     {
    //       type: 'category',
    //       label: 'Google Cloud',
    //       items: [
    //         {
    //           type: 'doc',
    //           id: 'template-library/google/simple-vpc',
    //           label: 'Simple VPC',
    //           // customProps: {
    //           //   icon: '/img/google-cloud-icon.png',  // Path to your Google Cloud icon
    //           //   description: 'Set up a simple VPC in Google Cloud with necessary network settings.',
    //           // },
    //         },
    //       ],
    //     },
    //   ],
    // },
  ],
};

export default sidebars;
